# Copyright 2021 Vitalant
# Author: Vincent Chiang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this software. If not, see <http://www.gnu.org/licenses/>.

# example config file

class Config(object):
	DEBUG = ...
	ENV = ...
	TESTING = ...
	SECRET_KEY = ...
	SECURITY_PASSWORD_SALT = ...
	SQL_ALCHEMY_DATABASE_URI = ...

	ADMIN_EMAIL = ...
	ADMIN_PASS = ...

	SERVER_URL = ...
	DATABASE_NAME = ...
	PARTIAL_VARIABLE = ...
	PRIMARY = ...
	DATE_COLUMN = ...
	DATE_FORMAT = ...
	PREVIEW_NUM = ...

	WINDOWS_AUTHENTICATION = ...

	DB_USER = ...

	DB_PASS = ...

	SESSION_COOKIE_SECURE = ...